# Generated by Django 2.2 on 2020-04-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
