# Generated by Django 2.2 on 2020-04-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
    ]
